### ISSUE TITLE
comp68 and comp78 entries

### ISSUE THREAD

**Issue by ruslankotl** [C-H-activation/ICB-ml-training#2]
Hello,

I was extracting the data on relative barriers for `comp68` and `comp78` and noticed the relative barriers and positions do not look right and are not included in `tsa.txt`. Did you discard these points in training?

Best wishes,

Ruslan

**Comment by f3rmion** [comment]
Hi @ruslankotl,

Sorry for the late answer (please ping me next time).
If those records are not present in `tsa.txt` then they were discarded respectively.
Let me remove the compounds from the repo.

Cheers,
Eike

**Comment by f3rmion** [comment]
Fixed in #3
